export const GET_USER = 'getUser'
export const USER = 'user'
export const CONNECTED = 'connected'
export const DISCONNECTED = 'disconnected'
export const CONNECTING = 'connecting'
export const CONNECTION_STATUS = 'connectionStatus'
